id: I522D7324
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T19:33:22+00:00'
last_modified: '2022-06-08T13:47:19.134057+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27408
  title: མ་ཎི་མཆོད་པའི་འཆམ་དབྱངས་རྒྱས་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4FCC:
      image_group_id: I4324
      title: ''
      total_pages: 122
      order: 1
      base_file: 4FCC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
