id: I522D7324
legacy_id: P010463
ocr_import_info:
  bdrc_scan_id: W27408
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T19:32:35'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T07:14:56.899510+00:00'
last_modified: 2022-09-02 15:15:07.584596
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27408
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27408
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མ་ཎི་མཆོད་པའི་འཆམ་དབྱངས་རྒྱས་པ།
  author: གུ་རུ་ཆོས་དབང་།
statistics:
  ocr_word_mean_confidence_index: 0.7607734683966908
  ocr_word_median_confidence_index: 0.8399999737739563
quality: null
bases:
  I4324:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4324
      total_pages: 122
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4324.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7607734683966908
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
