id: P010463
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W27408
  title: མ་ཎི་མཆོད་པའི་འཆམ་དབྱངས་རྒྱས་པ
  author: ''
  volumes:
    e71c32309f8b44c6a87ad51b0a27931a:
      image_group_id: I4324
      title: ''
      volume_number: 1
      total_pages: 122
      base_file: v001.txt
